### ISSUE TITLE
what is needed for upgrading this code into word2vec version

### ISSUE THREAD

**Issue by sjhddh** [dennybritz/cnn-text-classification-tf#10]
As is stated in @dennybritz 's blog, this code can also be used together with a pre-trained word2vec.

I am thinking about how to make the modification for that.

The obvious steps that I came across are:
1. instead of padding and indexing vocabulary, use a fix sized w2v vector to represent the sentence.
2. remove the embedding layer on TextCNN class.

Is that all? Did I misunderstand something?

Thx

**Comment by dennybritz** [comment]
I don't think you need to change the vocabulary building or remove the embedding. I think what you need to do this is:

1. Set the embedding dimension to 300 (or whatever pre-trained word2vec you want to use)
2. Build the "initial" `vocab_size x embedding_sim` embedding matrix based on word2vec. You do that by iterating through the downloaded word2vec vectors and for each vocabulary word set the appropriate column in the matrix. Initialize words that are not in word2vec randomly.
3. Before training, initialize the embedding matrix with the one you computed in step 2 using `W.assign`

**Comment by lenhhoxung86** [comment]
Hello @dennybritz , I think there will be two steps here:
1. Change the parameter `embedding_dim` in file `train.py`
2. Change the following code in file `text_cnn.py`:
```
# Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
            W = tf.Variable(
                tf.random_uniform([vocab_size, embedding_size], -1.0, 1.0),
                name="W")
            self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)
```
Instead of building the matrix with random entries, now we build the matrix with row vectors from `vectors.bin` taken from word2vec, right?
I also have another question. In your code, you initialize matrix entries with random numbers. How that possible? Each time we run `./train.py`, a new feature matrix will be created for a sentence because we randomly initialize the vocab matrix, is that right?

**Comment by dennybritz** [comment]
> Instead of building the matrix with random entries, now we build the matrix with row vectors from vectors.bin taken from word2vec, right?

You can do it either way. You can either change the initialization of the matrix, or you can leave the random initialization and then overwrite the value. Nothing is assigned/initialized in the code snippet you posted, it just builds the computation graph. You may want to read the Tensorflow documentation on how initialization and variable assignment works. Then it will become clear.

> I also have another question. In your code, you initialize matrix entries with random numbers. How that possible? Each time we run ./train.py, a new feature matrix will be created for a sentence because we randomly initialize the vocab matrix, is that right?

I'm not sure if I understand the question. Yes, the matrices are initialized randomly. And yes, at each run the random initialization will be different. If you want 100% reproducible results you can use [tf.set_random_seed](https://www.tensorflow.org/versions/r0.7/api_docs/python/constant_op.html#set_random_seed)

**Comment by lenhhoxung86** [comment]
> Nothing is assigned/initialized in the code snippet you posted
Yes because I just copy your code
> I'm not sure if I understand the question
I mean for a word, a random vector of embedding_dim is assigned for, but we don't have the correlation between that word and the random values. Can you give me a reason why you do that?

**Comment by sjhddh** [comment]
@dennybritz Thx, I've tried. and it works perfects! awesome.

**Comment by ferfervi** [comment]
Hi @sjhddh

Would you mind to share the code for embedding the word2vec if you managed to do it?

I have a pretrained word2vec matrix "embedding_matrix" with one text sentence per row and n_dim(300) columns using gensim.

I assign it to "W" after defining it. However I get an error when processing "tf.nn.embedding_lookup(W, self.input_x)"
@dennybritz , I followed your indications assining the pretrained word2vec matrix usint W.assign. Please, let me know if you how to solve it. thanks in advance!

     ```
   # Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
           W = tf.Variable(tf.random_uniform([embedding_matrix.shape[0], embedding_size], -1.0, 1.0),name="W")
           W.assign(embedding_matrix)

```
            self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)

        # Create a convolution + maxpool layer for each filter size
        #...
  

- Error:

tensorflow.python.framework.errors.InvalidArgumentError: indices[0,10] = -1 is not in [0, 50000)
	 [[Node: embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W/read, _recv_input_x_0)]]
Caused by op 'embedding/embedding_lookup', defined at:
 File "/Users/Fer/Development/MASTERBD/TFM/cnn-text-classification-tf/text_cnn.py", line 46, in __init__
    self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)

**Comment by ferfervi** [comment]
Hi @sjhddh

Would you mind to share the code for embedding the word2vec if you managed to do it?

I have a pretrained word2vec matrix "embedding_matrix" with one text sentence per row and n_dim(300) columns using gensim.

I assign it to "W" after defining it. However I get an error when processing "tf.nn.embedding_lookup(W, self.input_x)"
@dennybritz , I followed your indications assining the pretrained word2vec matrix usint W.assign. Please, let me know if you how to solve it. thanks in advance!

```
   # Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
           W = tf.Variable(tf.random_uniform([embedding_matrix.shape[0], embedding_size], -1.0, 1.0),name="W")
           W.assign(embedding_matrix)

            self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)

        # Create a convolution + maxpool layer for each filter size
        #...
```
- Error:

tensorflow.python.framework.errors.InvalidArgumentError: indices[0,10] = -1 is not in [0, 50000)
	 [[Node: embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W/read, _recv_input_x_0)]]
Caused by op 'embedding/embedding_lookup', defined at:
 File "/Users/Fer/Development/MASTERBD/TFM/cnn-text-classification-tf/text_cnn.py", line 46, in __init__
    self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)

**Comment by ferfervi** [comment]
Hi @sjhddh

Would you mind to share the code for embedding the word2vec if you managed to do it?

I have a pretrained word2vec matrix "embedding_matrix" with one text sentence per row and n_dim(300) columns using gensim.

I assign it to "W" after defining it. However I get an error when processing "tf.nn.embedding_lookup(W, self.input_x)"
@dennybritz , I followed your indications assining the pretrained word2vec matrix usint W.assign. Please, let me know if you how to solve it. thanks in advance!

```
   # Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
           W = tf.Variable(tf.random_uniform([embedding_matrix.shape[0], embedding_size], -1.0, 1.0),name="W")
           W.assign(embedding_matrix)

            self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)
            self.embedded_chars_expanded = tf.expand_dims(self.embedded_chars, -1)

        # Create a convolution + maxpool layer for each filter size
        #...
```
- Error:

tensorflow.python.framework.errors.InvalidArgumentError: indices[0,10] = -1 is not in [0, 50000)
	 [[Node: embedding/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding/W"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding/W/read, _recv_input_x_0)]]
Caused by op 'embedding/embedding_lookup', defined at:
 File "cnn-text-classification-tf/text_cnn.py", line 46, in __init__
    self.embedded_chars = tf.nn.embedding_lookup(W, self.input_x)

**Comment by AndrewShf** [comment]
Will the below code work? I test it, and the accuracy rises a little, and I doubt it's correctness.
`
            sess.run(tf.global_variables_initializer())
            if FLAGS.word2vec:
                # initial matrix with random uniform
                initW = np.random.uniform(-0.25,0.25,(len(vocab_processor.vocabulary_), FLAGS.embedding_dim))
                # load any vectors from the word2vec
                print("Load word2vec file {}\n".format(FLAGS.word2vec))
                model = word2vec.load('mini_train_300.bin')
                # index_word = {}
                # enumerate words from the vocab list
                for i in range(len(model.vocab)):
                    # get the word's index from the vocab_processor
                    idx = vocab_processor.vocabulary_.get(model.vocab[i])
                    # give its word vector
                    initW[idx] = model.vectors[i]
                sess.run(cnn.W.assign(initW))
`

**Comment by AndrewShf** [comment]
Will the below code work? I test it, and the accuracy rises a little, so I doubt its correctness. Apart from this, other codes in the original project are not changed.
<pre>
            sess.run(tf.global_variables_initializer())
            if FLAGS.word2vec:
                # initial matrix with random uniform
                initW = np.random.uniform(-0.25,0.25,(len(vocab_processor.vocabulary_), FLAGS.embedding_dim))
                # load any vectors from the word2vec
                print("Load word2vec file {}\n".format(FLAGS.word2vec))
                model = word2vec.load('mini_train_300.bin')
                # index_word = {}
                # enumerate words from the vocab list
                for i in range(len(model.vocab)):
                    # get the word's index from the vocab_processor
                    idx = vocab_processor.vocabulary_.get(model.vocab[i])
                    # give its word vector
                    initW[idx] = model.vectors[i]
                sess.run(cnn.W.assign(initW))
</pre>
