### ISSUE TITLE
How to get the classification result?

### ISSUE THREAD

**Issue by wyqnumber** [dennybritz/cnn-text-classification-tf#2]
Code: 
     self.predictions = tf.argmax(self.scores, 1, name="predictions")

But, I want to get the classification result, such as [1, 0, 1, 1, ...], How to get it?
Thank you!

**Comment by dennybritz** [comment]
`self.predictions` is the classification result for a multinomial classification problem. For example, if you get "1", that's equivalent to `[0,1]. ` ` [1, 0, 1, 1, ...]` is not possible because only one class can be predicted. If you want to get the probabilities you can use `self.scores` and use a softmax on that.
