### ISSUE TITLE
Great difference between train+dev and test accuracy !?

### ISSUE THREAD

**Issue by tmchojo** [dennybritz/cnn-text-classification-tf#63]
While training with the sample (rt-polaritydata), train+dev accuracy is as follows.

Train
> 2017-01-26T06:58:37.631166: step 501, loss 0.556401, acc 0.75
> 2017-01-26T06:58:37.679757: step 502, loss 0.679618, acc 0.578125
> 2017-01-26T06:58:37.727246: step 503, loss 0.647241, acc 0.640625
> 2017-01-26T06:58:47.615602: step 701, loss 0.759469, acc 0.578125
> 2017-01-26T06:58:47.661450: step 702, loss 0.45458, acc 0.828125
> 2017-01-26T06:58:47.707539: step 703, loss 0.531736, acc 0.78125

Dev
> 2017-01-26T05:13:06.948762: step 500, loss 0.611592, acc 0.667917
> 2017-01-26T05:13:16.855488: step 700, loss 0.585405, acc 0.688555

But when evaluating, test accuracy more more higher than aboves.

Test
> Total number of test examples: 10662
> Accuracy: 0.841587
> Total number of test examples: 10662
> Accuracy: 0.894579

Why this problem happens?
In my data, test accuracy is very lower than train+dev.

I think the **tf.global_variables()** does not cover all variables at 0.12.0, so removed it.
But same results are occured.

**Comment by qwaider** [comment]
Well, actually i am facing the same problem, but i discovered that when running the eval.py, load data function is grouping the train+dev to be evaluated, so you don't evaluate your model against just the testset, but testset+train.

That is what i got, and to fix it temporarily to see the performance on testset, change the return of  def load_data_and_labels(self): to be         return [x_dev, y_dev,classes] instead of return [x_all, y_all,classes]

**Comment by tmchojo** [comment]
I already know that data of the train.py and the eval.py are same. Default dev percentage is 0.1, so test accuracy must be 9:1 ratio of train and dev accuracy. But above example is not.
